# Generated by Django 5.2.8 on 2025-11-26 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penguin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('purple', 'purple'), ('pink', 'pink'), ('orange', 'ornage'), ('yellow', 'yellow')], default='red', max_length=50)),
                ('name', models.CharField(max_length=15)),
                ('created_date', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penguin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
